"""Identity construction under the frozen contract — T70, T71, T72, T79, T80, T86.

Every sensitivity assertion here mutates **raw input** and invokes the builder
against the resolved contract. No test substitutes a computed digest, hand-writes a
variant id, or edits a stored basis: doing so would demonstrate that a field can be
changed, which nobody doubts, rather than that the identity is constructed from the
configuration, which is the claim (I14).

Every test runs under `netguard`'s `guarded` decorator with credentials absent.
"""

from __future__ import annotations

import base64
import copy
import hashlib

from t4 import identity, jcs, manifest
from t4.identity import IdentityError, SecretBoundaryViolation, VariantSelectionError
from tests.netguard import guarded
from tests.util import raises


def _contract() -> dict:
    _path, raw, _digest = manifest.resolve(manifest.ROLE_CONTRACT)
    return jcs.parse(raw)


def _dimension(contract: dict, name: str) -> dict:
    return next(d for d in contract["dimensions"] if d["dimension"] == name)


def _raw_of(contract: dict, dimension: str, vector_id: str) -> dict:
    vector = next(v for v in _dimension(contract, dimension)["vectors"]
                  if v["vector_id"] == vector_id)
    return jcs.parse(base64.b64decode(vector["raw_input_b64"], validate=True))


# --------------------------------------------------------------------------- #
# T80 — every dimension and every variant, reproduced end to end
# --------------------------------------------------------------------------- #

@guarded
def test_t80_builder_reproduces_every_contract_vector():
    """Vectors are consumed from the contract, never regenerated by the builder."""
    contract = _contract()
    seen = 0
    for entry in contract["dimensions"]:
        for vector in entry["vectors"]:
            seen += 1
            raw = jcs.parse(base64.b64decode(vector["raw_input_b64"], validate=True))
            built = identity.build_identity(entry["dimension"], raw, contract)
            assert built == vector["expected_identity"], vector["vector_id"]
            expected_bytes = base64.b64decode(vector["expected_basis_bytes_b64"],
                                              validate=True)
            assert jcs.serialize(built["basis"]) == expected_bytes, vector["vector_id"]
            assert built["digest"] == vector["expected_digest"], vector["vector_id"]
    assert seen == 15

    # A dimension or variant with no vector is a failure, not an omission.
    for entry in contract["dimensions"]:
        assert entry["vectors"], entry["dimension"]
        for variant in entry["variants"] or []:
            assert any(v["variant_id"] == variant["variant_id"]
                       for v in entry["vectors"]), variant["variant_id"]


# --------------------------------------------------------------------------- #
# T70 / T71 — the digest is recomputed, and absence is digested
# --------------------------------------------------------------------------- #

@guarded
def test_t70_every_identity_digest_is_sha256_of_its_canonical_basis():
    contract = _contract()
    for entry in contract["dimensions"]:
        for vector in entry["vectors"]:
            built = identity.build_identity(
                entry["dimension"],
                jcs.parse(base64.b64decode(vector["raw_input_b64"], validate=True)),
                contract)
            assert built["digest"] == hashlib.sha256(
                jcs.serialize(built["basis"])).hexdigest()


@guarded
def test_t71_absence_is_digested_and_two_dimensions_absences_differ():
    contract = _contract()
    absent_prompt = identity.build_identity("prompt", {"present": False}, contract)
    absent_context = identity.build_identity("context", {"present": False}, contract)

    assert absent_prompt["digest"] is not None
    assert absent_prompt["basis"]["basis_kind"] == "absence"
    assert absent_prompt["presence"] == "absent"
    assert absent_prompt["resolution_state"] == "explicitly_disabled"
    # Two absences of one dimension are equal; absences of two dimensions are not,
    # because `dimension` sits inside the basis.
    assert identity.build_identity("prompt", {"present": False}, contract) == absent_prompt
    assert absent_prompt["digest"] != absent_context["digest"]


@guarded
def test_t71b_a_present_input_cannot_be_recorded_as_absent():
    """Construction-level: a false absence fails parity, it is not merely unlikely."""
    contract = _contract()
    raw = {"bytes_b64": base64.b64encode(b"a real prompt").decode(), "present": True}
    built = identity.build_identity("prompt", raw, contract)
    assert built["presence"] == "present"
    assert built["basis"]["basis_kind"] == "content_reference"

    claimed_absent = identity.build_identity("prompt", {"present": False}, contract)
    assert claimed_absent != built, "a record asserting absence for this input fails parity"


@guarded
def test_absence_is_refused_where_the_contract_does_not_permit_it():
    contract = _contract()
    with raises(IdentityError):
        identity.build_identity("workload", {"present": False}, contract)


# --------------------------------------------------------------------------- #
# T79 — content reference, including the zero-length case
# --------------------------------------------------------------------------- #

@guarded
def test_t79_present_empty_is_representable_and_distinct_from_absent():
    contract = _contract()
    empty = {"bytes_b64": "", "present": True}
    empty_prompt = identity.build_identity("prompt", empty, contract)
    empty_context = identity.build_identity("context", empty, contract)

    # (a)(b) present, content_reference, no parameters, zero length, computed digest
    for built in (empty_prompt, empty_context):
        assert built["presence"] == "present"
        assert built["basis"]["basis_kind"] == "content_reference"
        assert built["basis"]["parameters"] == []
        assert built["basis"]["content"]["byte_length"] == 0
        assert built["basis"]["content"]["content_digest"] == \
            hashlib.sha256(b"").hexdigest()

    # (d) the same zero-length bytes give the same content digest — as they must
    assert empty_prompt["basis"]["content"]["content_digest"] == \
        empty_context["basis"]["content"]["content_digest"]
    # (e) but the identity digests differ, because dimension is inside the basis
    assert empty_prompt["digest"] != empty_context["digest"]
    # and present-empty differs from absent for one dimension
    assert empty_prompt["digest"] != \
        identity.build_identity("prompt", {"present": False}, contract)["digest"]


@guarded
def test_content_digest_and_length_follow_the_bytes():
    contract = _contract()
    payload = "café — a non-ASCII payload".encode("utf-8")
    built = identity.build_identity(
        "workload", {"bytes_b64": base64.b64encode(payload).decode(), "present": True},
        contract)
    assert built["basis"]["content"]["byte_length"] == len(payload)
    assert built["basis"]["content"]["content_digest"] == \
        hashlib.sha256(payload).hexdigest()

    one_byte_more = payload + b"!"
    other = identity.build_identity(
        "workload",
        {"bytes_b64": base64.b64encode(one_byte_more).decode(), "present": True},
        contract)
    assert other["digest"] != built["digest"]


# --------------------------------------------------------------------------- #
# T63 / T64 / T72 / T74 — sensitivity, by mutating raw input
# --------------------------------------------------------------------------- #

@guarded
def test_t63_every_configured_policy_dimension_is_sensitive_to_its_raw_configuration():
    """Only two policy dimensions are configured here; the other three are unobservable."""
    contract = _contract()

    dispatch = _raw_of(contract, "dispatch", "dispatch-v1")
    base = identity.build_identity("dispatch", dispatch, contract)
    for mutation in (
        {"order": ["openai", "gemini"]},        # a different call order
        {"mode": "parallel"},                   # a different dispatch mode
        {"configurable": True},                 # configured-on versus configured-off
    ):
        mutated = dict(dispatch, **mutation)
        rebuilt = identity.build_identity("dispatch", mutated, contract)
        assert rebuilt["digest"] != base["digest"], mutation
        assert rebuilt["basis"]["parameters"] != base["basis"]["parameters"]

    fallback = _raw_of(contract, "fallback", "fallback-v1")
    base = identity.build_identity("fallback", fallback, contract)
    # A configured "disabled" and a configured "enabled" state must differ.
    enabled = identity.build_identity("fallback", dict(fallback, enabled=True), contract)
    assert enabled["digest"] != base["digest"]
    assert enabled["basis"]["parameters"] != base["basis"]["parameters"]


@guarded
def test_t64_component_implementation_identity_is_sensitive_to_the_environment():
    contract = _contract()
    raw = _raw_of(contract, "implementation", "implementation-v1")
    base = identity.build_identity("implementation", raw, contract)

    # A last-digit change in one dependency version moves the digest.
    mutated = copy.deepcopy(raw)
    mutated["distributions"]["numpy_version"] = "2.5.2"
    assert identity.build_identity("implementation", mutated, contract)["digest"] \
        != base["digest"]

    # So does the interpreter version.
    mutated = copy.deepcopy(raw)
    mutated["python"] = "3.12.14"
    assert identity.build_identity("implementation", mutated, contract)["digest"] \
        != base["digest"]


@guarded
def test_t72_the_key_set_is_closed_in_both_directions():
    contract = _contract()
    raw = _raw_of(contract, "implementation", "implementation-v1")

    missing = copy.deepcopy(raw)
    del missing["distributions"]["numpy_version"]
    with raises(IdentityError):
        identity.build_identity("implementation", missing, contract)

    extra = copy.deepcopy(raw)
    extra["distributions"]["unreviewed_version"] = "1.0.0"
    with raises(IdentityError):
        identity.build_identity("implementation", extra, contract)


@guarded
def test_t74_parameter_values_are_canonical_typed_strings():
    contract = _contract()
    built = identity.build_identity(
        "dispatch", _raw_of(contract, "dispatch", "dispatch-v1"), contract)
    by_key = {p["key"]: p for p in built["basis"]["parameters"]}

    assert by_key["configurable"] == {"key": "configurable", "value": "false",
                                      "value_type": "boolean"}
    assert by_key["order"]["value"] == "gemini,openai"   # one representation per value
    assert all(isinstance(p["value"], str) for p in built["basis"]["parameters"])
    # keys sorted ascending, unique
    keys = [p["key"] for p in built["basis"]["parameters"]]
    assert keys == sorted(keys, key=lambda k: k.encode("utf-16-be"))
    assert len(set(keys)) == len(keys)

    # a value whose Python type disagrees with the declared type is refused
    with raises(IdentityError):
        identity.build_identity(
            "dispatch",
            dict(_raw_of(contract, "dispatch", "dispatch-v1"), configurable="false"),
            contract)


# --------------------------------------------------------------------------- #
# T86 — variant selection
# --------------------------------------------------------------------------- #

@guarded
def test_t86_selection_is_unique_and_has_no_default_or_fallback():
    contract = _contract()
    entry = _dimension(contract, "implementation")
    assert identity.select_variant(entry, {}) == "impl-all"

    # Ambiguous: two variants that can both match is an error, not a precedence rule.
    ambiguous = copy.deepcopy(entry)
    clone = copy.deepcopy(ambiguous["variants"][0])
    clone["variant_id"] = "impl-clone"
    ambiguous["variants"].append(clone)
    with raises(VariantSelectionError):
        identity.select_variant(ambiguous, {})

    # Unmatched: no variant matches, and no default variant is applied.
    unmatched = copy.deepcopy(entry)
    unmatched["variants"][0]["selector"] = [
        {"discriminator": "component", "match": "exact", "value": "never-matches"}]
    with raises(VariantSelectionError):
        identity.select_variant(unmatched, {"component": "retrieval"})


# --------------------------------------------------------------------------- #
# §2A — the classification filter refuses rather than omits
# --------------------------------------------------------------------------- #

@guarded
def test_a_security_material_key_is_refused_not_silently_omitted():
    """§2A S5: an omission would produce a basis claiming a completeness it lacks."""
    contract = copy.deepcopy(_contract())
    entry = _dimension(contract, "implementation")
    variant = entry["variants"][0]
    variant["keys"][0]["key"] = "openai_api_key"
    variant["keys"].sort(key=lambda k: k["key"].encode("utf-16-be"))

    raw = copy.deepcopy(_raw_of(_contract(), "implementation", "implementation-v1"))
    raw["distributions"]["openai_api_key"] = raw["distributions"].pop("google_genai_version")

    with raises(SecretBoundaryViolation):
        identity.build_identity("implementation", raw, contract)


@guarded
def test_an_unobservable_dimension_refuses_a_locally_set_value():
    """A contract gap is reported, not absorbed: the contract says nothing is set."""
    contract = _contract()
    assert identity.build_identity("retry", {"locally_set": False}, contract)[
        "resolution_state"] == "provider_managed_unobservable"
    with raises(IdentityError):
        identity.build_identity("retry", {"locally_set": True}, contract)
