"""Voice of Emergence — thin Streamlit chat client over the E4 pilot API.

No reasoning, retrieval, model, MIVE, or governance logic here: this module
only drives POST /pilot/sessions[, /turn, /close] and renders the backend's
public response fields. Run: streamlit run app.py
(VOICE_OF_EMERGENCE_API_BASE_URL is read server-side, never displayed.)
"""

from __future__ import annotations

import json
from pathlib import Path

import streamlit as st

import pilot_client as pc

LOADING_TEXT = "One moment…"
WELCOME_TEXT = "Ask a question in your own words, or begin with one of these."
BASE_QUESTIONS_PATH = Path(__file__).resolve().parent / "base_questions.json"
# Presentation Cassette PC1 (generated by tools/generate_presentation_cassette.py):
# Works navigation, readable source labels and the suggestion blocklist.
PRESENTATION_CASSETTE_PATH = Path(__file__).resolve().parent / "presentation_cassettes" / "pc1_staging.json"
PRESENTATION_CASSETTE_SCHEMA = "VOE_PRESENTATION_CASSETTE_V1"
HANDOFF_QUERY_PARAM = "q"
SAFE_ERROR_TEXT = "Voice of Emergence could not complete this request. Please try again."
CLARIFY_TEXT = "Could you say a little more about what you'd like to know?"
# v0.3 surface: the natural answer stays on top; sources and every technical
# disclosure move, unchanged, into two collapsed sections.
SOURCES_HEADING = "Sources"
ABOUT_HEADING = "About this answer"
OPEN_POINTS_HEADING = "Open points"
SOURCE_LINKS_HEADING = "How the sources connect"
# Shown on the main surface ONLY when the text was not composed (FALLBACK or no
# presentation step), so stated uncertainty is never hidden behind a collapse.
FALLBACK_OPEN_POINTS_PREFIX = "Still open: "
PRESENTATION_LABELS = {
    "COMPOSED": "Presented in the Voice of Emergence style from the verified interpretation.",
    "FALLBACK": "Shown in standard form.",
}
MAX_SUGGESTIONS = 3
MAX_WORKS_SUGGESTIONS = 2

st.set_page_config(page_title="Voice of Emergence")
# Presentation-only styling: hide chat avatars and keep the title's layout
# space while making it invisible (#voice-of-emergence is Streamlit's
# auto-generated anchor for the st.title below).
st.markdown(
    """
    <style>
    [data-testid="stChatMessageAvatarUser"],
    [data-testid="stChatMessageAvatarAssistant"] {
        display: none !important;
    }
    #voice-of-emergence {
        visibility: hidden;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


def _init_state() -> None:
    st.session_state.setdefault("pilot_session_id", None)
    st.session_state.setdefault("messages", [])
    st.session_state.setdefault("request_in_flight", False)
    st.session_state.setdefault("last_error", None)
    st.session_state.setdefault("pending_question", None)
    st.session_state.setdefault("url_handoff_consumed", False)


def _load_base_questions() -> dict[str, str]:
    """Allowlisted starter questions, id -> text, in file order.

    Surface copy only. A missing or malformed file yields no starters rather
    than breaking the chat.
    """
    try:
        raw = json.loads(BASE_QUESTIONS_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if not isinstance(raw, list):
        return {}
    questions: dict[str, str] = {}
    for item in raw:
        if not isinstance(item, dict):
            continue
        qid, text = item.get("id"), item.get("text")
        if isinstance(qid, str) and qid and isinstance(text, str) and text.strip():
            questions.setdefault(qid, text.strip())
    return questions


def _load_json(path: Path):
    """A missing or malformed presentation file yields None, never a crash."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _load_presentation_cassette() -> tuple[list[dict], dict, dict[str, str]]:
    """Works navigation items (in Q order), blocklist and source labels from PC1.

    Presentation-only. Fails closed: a missing, malformed, non-staging or
    non-starter-only cassette yields no Works navigation and no labels, so
    the client shows the starter only.
    """
    raw = _load_json(PRESENTATION_CASSETTE_PATH)
    if not (isinstance(raw, dict) and raw.get("schema") == PRESENTATION_CASSETTE_SCHEMA
            and raw.get("environment") == "staging" and raw.get("opening") == "STARTER_ONLY"):
        return [], {}, {}
    items = [
        m for m in raw.get("members") or []
        if isinstance(m, dict) and isinstance(m.get("object_id"), str)
        and isinstance(m.get("question"), str) and m["question"].strip()
    ]
    blocked = raw.get("suggestion_blocklist") if isinstance(raw.get("suggestion_blocklist"), dict) else {}
    labels = raw.get("source_labels") if isinstance(raw.get("source_labels"), dict) else {}
    labels = {k: v for k, v in labels.items() if isinstance(k, str) and isinstance(v, str) and v}
    return items, blocked, labels


def _key(text: str) -> str:
    return " ".join(text.split()).casefold()


_init_state()
BASE_QUESTIONS = _load_base_questions()
WORKS_ITEMS, WORKS_BLOCKED, SOURCE_LABELS = _load_presentation_cassette()
WORKS_BY_OBJECT = {i["object_id"]: i for i in WORKS_ITEMS}
_BLOCKED_QUESTION_KEYS = {_key(q) for q in WORKS_BLOCKED.get("questions") or [] if isinstance(q, str)}
_BLOCKED_PHRASES = tuple(p.casefold() for p in WORKS_BLOCKED.get("phrases") or [] if isinstance(p, str) and p)


def _is_blocked_suggestion(text: str) -> bool:
    """Held/pending Works material never surfaces as a suggestion."""
    key = _key(text)
    return key in _BLOCKED_QUESTION_KEYS or any(p in key for p in _BLOCKED_PHRASES)

try:
    _CLIENT = pc.PilotClient()
except pc.ConfigurationError:
    st.title("Voice of Emergence")
    st.error(SAFE_ERROR_TEXT)
    st.stop()


def _new_conversation() -> None:
    session_id = st.session_state.pilot_session_id
    if session_id:
        try:
            _CLIENT.close_session(session_id)
        except pc.PilotClientError:
            pass
    st.session_state.messages = []
    st.session_state.pilot_session_id = None
    st.session_state.request_in_flight = False
    st.session_state.pending_question = None
    st.session_state.last_error = None
    st.rerun()


def _object_id(item: dict) -> str | None:
    """The Works object id behind an evidence row ("TW-OBJ-0047::c0" -> "TW-OBJ-0047")."""
    for field in ("document_id", "chunk_id"):
        value = item.get(field)
        if isinstance(value, str) and value.startswith("TW-OBJ-"):
            return value.split("::", 1)[0]
    return None


def _source_name(item: dict) -> str:
    source = item.get("source") or ""
    return SOURCE_LABELS.get(source) or item.get("title") or source or "Source"


def _source_reference(item: dict) -> str:
    works = WORKS_BY_OBJECT.get(_object_id(item) or "")
    if works and isinstance(works.get("question_ref"), str):
        return works["question_ref"]
    page = item.get("page")
    if page not in (None, ""):
        return f"p. {page}"
    reference = item.get("chunk_id") or item.get("document_id")
    return str(reference) if reference not in (None, "") else "—"


def _render_source_item(item: dict) -> None:
    st.markdown(f"**{_source_name(item)}** · {_source_reference(item)}")
    st.markdown(item.get("excerpt") or "")
    st.divider()


def _render_about(msg: dict) -> None:
    """Every technical disclosure, unchanged, in one collapsed section."""
    label = PRESENTATION_LABELS.get(msg.get("presentation_status"))
    if label:
        st.caption(label)
    if msg.get("disclaimer"):
        st.caption(msg["disclaimer"])
    uncertainty = msg.get("uncertainty") or []
    if uncertainty:
        st.markdown(f"**{OPEN_POINTS_HEADING}**")
        st.markdown("\n".join(f"- {item}" for item in uncertainty))
    links = [(item, item.get("claim_linkage")) for item in msg.get("evidence") or []]
    links = [(item, claim) for item, claim in links if claim]
    if links:
        st.markdown(f"**{SOURCE_LINKS_HEADING}**")
        st.markdown("\n".join(
            f"- {_source_name(item)} · {_source_reference(item)}: {claim}" for item, claim in links
        ))


def _render_message(msg: dict) -> None:
    with st.chat_message(msg["role"]):
        kind = msg["kind"]
        if kind == "user":
            st.write(msg["content"])
        elif kind == "answer":
            st.write(msg["primary_answer"])
            uncertainty = msg.get("uncertainty") or []
            if uncertainty and msg.get("presentation_status") != "COMPOSED":
                # Not composed: the text shown is the standard answer, so the
                # stated uncertainty stays visible, compactly and verbatim.
                st.caption(FALLBACK_OPEN_POINTS_PREFIX + " · ".join(uncertainty))
            evidence = msg.get("evidence") or []
            if evidence:
                with st.expander(f"{SOURCES_HEADING} ({len(evidence)})", expanded=False):
                    for item in evidence:
                        _render_source_item(item)
            with st.expander(ABOUT_HEADING, expanded=False):
                _render_about(msg)
        elif kind == "clarify":
            st.write(CLARIFY_TEXT)
        elif kind == "error":
            st.write(SAFE_ERROR_TEXT)


def _process_turn(question: str) -> None:
    try:
        if st.session_state.pilot_session_id is None:
            st.session_state.pilot_session_id = _CLIENT.create_session()
        try:
            outcome = _CLIENT.run_turn(st.session_state.pilot_session_id, question)
        except pc.SessionNotFoundError:
            # Stale in-memory pilot session: recover exactly once.
            st.session_state.pilot_session_id = _CLIENT.create_session()
            outcome = _CLIENT.run_turn(st.session_state.pilot_session_id, question)
    except pc.PilotClientError:
        st.session_state.messages.append({"role": "assistant", "kind": "error"})
        st.session_state.last_error = SAFE_ERROR_TEXT
        return

    st.session_state.last_error = None
    if isinstance(outcome, pc.ClarifyTurn):
        st.session_state.messages.append({"role": "assistant", "kind": "clarify"})
    else:
        st.session_state.messages.append({
            "role": "assistant",
            "kind": "answer",
            "primary_answer": outcome.primary_answer,
            "disclaimer": outcome.disclaimer,
            "evidence": list(outcome.evidence),
            "uncertainty": list(outcome.uncertainty),
            "presentation_status": outcome.presentation_status,
            "suggested_questions": list(outcome.suggested_questions),
        })


def _works_next_questions(answer: dict, asked: set[str]) -> list[str]:
    """Up to MAX_WORKS_SUGGESTIONS authorized Works questions for this answer.

    Deterministic and presentation-only: start from the Works objects in this
    answer's own sources, then their governed `related` links, then their
    neighbours in the Q&A series; keep only items flagged
    `navigable_after_answer`, never blocked, never already asked.
    """
    order = [i["object_id"] for i in WORKS_ITEMS]
    candidates: list[str] = []
    for item in answer.get("evidence") or []:
        oid = _object_id(item)
        if oid not in WORKS_BY_OBJECT:
            continue
        pos = order.index(oid)
        neighbours = [order[p] for p in (pos - 1, pos + 1) if 0 <= p < len(order)]
        candidates += [oid, *(WORKS_BY_OBJECT[oid].get("related") or []), *neighbours]
    picked: list[str] = []
    for oid in candidates:
        works = WORKS_BY_OBJECT.get(oid)
        if not works or works.get("navigable_after_answer") is not True:
            continue
        question = works["question"]
        if _key(question) in asked or _is_blocked_suggestion(question) or question in picked:
            continue
        picked.append(question)
        if len(picked) == MAX_WORKS_SUGGESTIONS:
            break
    return picked


def _next_questions(answer: dict) -> list[str]:
    """Works navigation first, then the presentation step's own suggestions."""
    asked = {_key(m["content"]) for m in st.session_state.messages if m.get("kind") == "user"}
    merged: list[str] = []
    seen: set[str] = set()
    for text in _works_next_questions(answer, asked) + list(answer.get("suggested_questions") or []):
        key = _key(text)
        if key in seen or key in asked or _is_blocked_suggestion(text):
            continue
        seen.add(key)
        merged.append(text)
        if len(merged) == MAX_SUGGESTIONS:
            break
    return merged


def _render_latest_suggestions() -> None:
    """Suggested next questions under the LATEST answer only, and only while
    no request is in flight. A click is an ordinary question: it goes through
    the one `_submit` path, nothing else. Unclicked suggestions leave no state."""
    messages = st.session_state.messages
    if st.session_state.request_in_flight or not messages:
        return
    latest_index = len(messages) - 1
    latest = messages[latest_index]
    if latest.get("kind") != "answer":
        return
    for n, suggestion in enumerate(_next_questions(latest)):
        if st.button(suggestion, key=f"suggest-{latest_index}-{n}"):
            _submit(suggestion)


def _submit(question: str) -> None:
    """The one submit path shared by typed input, starter buttons and URL handoff."""
    st.session_state.messages.append({"role": "user", "kind": "user", "content": question})
    st.session_state.pending_question = question
    st.session_state.request_in_flight = True
    st.rerun()


def _consume_url_handoff() -> None:
    """Auto-submit an allowlisted ?q=<id> once, then clear the parameter.

    Only ids from base_questions.json are honoured; the submitted text always
    comes from that file, never from the URL. Unknown ids are dropped.
    """
    if HANDOFF_QUERY_PARAM not in st.query_params:
        return
    question_id = st.query_params.get(HANDOFF_QUERY_PARAM)
    del st.query_params[HANDOFF_QUERY_PARAM]
    if st.session_state.url_handoff_consumed:
        return
    st.session_state.url_handoff_consumed = True
    question = BASE_QUESTIONS.get(question_id)
    if question and not st.session_state.messages and not st.session_state.request_in_flight:
        _submit(question)


_consume_url_handoff()

title_col, action_col = st.columns([5, 1])
with title_col:
    st.title("Voice of Emergence")
with action_col:
    if st.button("New conversation", disabled=st.session_state.request_in_flight):
        _new_conversation()

if not st.session_state.messages and not st.session_state.request_in_flight:
    st.write(WELCOME_TEXT)
    # Opening is STARTER ONLY (PC1): no Works entry questions.
    for question_id, question in BASE_QUESTIONS.items():
        if st.button(question, key=f"starter-{question_id}"):
            _submit(question)

for msg in st.session_state.messages:
    _render_message(msg)

_render_latest_suggestions()

prompt = st.chat_input("Ask a question", disabled=st.session_state.request_in_flight)

if prompt and not st.session_state.request_in_flight:
    _submit(prompt)

if st.session_state.request_in_flight and st.session_state.pending_question:
    with st.chat_message("assistant"):
        with st.spinner(LOADING_TEXT):
            try:
                _process_turn(st.session_state.pending_question)
            finally:
                st.session_state.pending_question = None
                st.session_state.request_in_flight = False
    st.rerun()
