"""ION PEL Phase 2B.1R3 — frozen v0.2.2 clarified output-contract constants.

These constants and enums are frozen by
`ION_PEL_PHASE2B0_4_UNKNOWN_ASSIGNMENT_POSITION_CLARIFICATION_FREEZE_v0.2.2.md`
(SHA-256 15d101da0420f6513162d51b4c9c2ffb259dc7fe32f73a6b2dc2f358d3891c21),
a positional clarification successor to
`ION_PEL_PHASE2B0_3_CONTRACT_CLARIFICATION_FREEZE_v0.2.1.md`
(SHA-256 523935e0cffb39440f3aa3096bf1dc1b6456159e15d362bef0bf34fe356791f0),
which itself succeeded
`ION_PEL_PHASE2B0_2_HARDENED_OUTPUT_CONTRACT_FREEZE_v0.2.md`
(SHA-256 87fbe0ce09cb43ae394a653be6b2d08ba62c4358b901b971569c65f4d57b8125),
which succeeded the historical
`ION_PEL_PHASE2B0_CHECKER_OUTPUT_CONTRACT_FREEZE_v0.1.md`. Nothing here may
change without a new frozen contract version.
"""

from __future__ import annotations

OUTPUT_CONTRACT_ID = "ION_PEL_SINGLE_TARGET_DEFECT_ADMISSION_V0_2_2"
PARSER_ID = "ION_PEL_SINGLE_TARGET_DEFECT_ADMISSION_PARSER"
PARSER_VERSION = "0.2.2"

PRIMARY_VERDICTS = ("YES", "NO", "UNRESOLVED")
CONFIDENCE_VALUES = ("HIGH", "MEDIUM", "LOW")
FINAL_RESULTS = ("MATERIAL_DEFECT_FOUND", "NO_MATERIAL_DEFECT_FOUND", "UNRESOLVED")
PARSE_STATUSES = ("PARSED", "PARTIAL", "UNPARSEABLE")
TRACE_KINDS = ("EXACT_EXTRACT", "CONTRACT_MAP", "NO_SOURCE_VALUE")
FIELD_STATES = ("PRESENT", "EXPLICIT_UNKNOWN", "MISSING", "AMBIGUOUS", "INVALID_VALUE")

DIAGNOSTIC_CODES = (
    "INVALID_UTF8",
    "UNKNOWN_FIELD",
    "DUPLICATE_FIELD",
    "CONFLICTING_FIELD",
    "INVALID_ENUM_VALUE",
    "MISSING_REQUIRED_FIELD",
    "MISSING_REQUIRED_SECTION",
    "UNSUPPORTED_OUTPUT_CONTRACT",
    "SOURCE_EVIDENCE_MISMATCH",
    "AMBIGUOUS_STRUCTURE",
)

__all__ = [
    "CONFIDENCE_VALUES",
    "DIAGNOSTIC_CODES",
    "FIELD_STATES",
    "FINAL_RESULTS",
    "OUTPUT_CONTRACT_ID",
    "PARSER_ID",
    "PARSER_VERSION",
    "PARSE_STATUSES",
    "PRIMARY_VERDICTS",
    "TRACE_KINDS",
]
